// Game setup
export const SETUP_GAME_FULL = 'SETUP_GAME_FULL';
export const SETUP_GAME_ENEMY_TYPE = 'SETUP_GAME_ENEMY_TYPE'; 
export const SETUP_GAME_AI_DIFFICULTY = 'SETUP_GAME_AI_DIFFICULTY';
export const SETUP_GAME_FLEET_TYPE = 'SETUP_GAME_FLEET_TYPE'; 
export const SETUP_GAME_BOARD_SIZE = 'SETUP_GAME_BOARD_SIZE';
export const SETUP_GAME_RANDOM = 'SETUP_GAME_RANDOM';