export const CHANGE_MODE = 'CHANGE_MODE';

//Game modes 
export const MODE_SPLASH_SCREEN = 'MODE_SPLASH_SCREEN';
export const MODE_MAIN_MENU = 'MODE_MAIN_MENU';
export const MODE_GAME = 'MODE_GAME';

//Game setup
export const SETUP_GAME_FULL = 'SETUP_GAME';
export const SETUP_GAME_ENEMY_TYPE = 'SETUP_GAME_ENEMY_TYPE'; 
export const SETUP_GAME_AI_DIFFICULTY = 'SETUP_GAME_AI_DIFFICULTY';
export const SETUP_GAME_FLEET_TYPE = 'SETUP_GAME_FLEET_TYPE'; 
export const SETUP_GAME_BOARD_SIZE = 'SETUP_GAME_BOARD_SIZE';
export const SETUP_GAME_RANDOM = 'SETUP_GAME_RANDOM';